#ifndef GUARD_CONSTANTS_REGIONS_H
#define GUARD_CONSTANTS_REGIONS_H

// Core-series regions
enum Region
{
    REGION_NONE,
    REGION_KANTO,
    REGION_JOHTO,
    REGION_HOENN,
    REGION_SINNOH,
    REGION_UNOVA,
    REGION_KALOS,
    REGION_ALOLA,
    REGION_GALAR,
    REGION_HISUI,
    REGION_PALDEA,
    REGION_GARDEN,
    REGIONS_COUNT,
};

enum KantoSubRegion
{
    KANTO_SUBREGION_KANTO,
    KANTO_SUBREGION_SEVII123,
    KANTO_SUBREGION_SEVII45,
    KANTO_SUBREGION_SEVII67,
    KANTO_SUBREGION_COUNT
};

enum GardenSubRegion
{
    GARDEN_SUBREGION_GARDEN,
    GARDEN_SUBREGION_DAWNSINGER,
    GARDEN_SUBREGION_LOCKWOOD,
    GARDEN_SUBREGION_SUMMERSPELL,
    GARDEN_SUBREGION_WILLOWBLOOM,
    GARDEN_SUBREGION_TITANBLAZE,
    GARDEN_SUBREGION_ROSESONG,
    GARDEN_SUBREGION_WISEMORE,
    GARDEN_SUBREGION_AUBERON,
    GARDEN_SUBREGION_COUNT
};

#endif  // GUARD_CONSTANTS_REGIONS_H
